### ISSUE TITLE
blade support

### ISSUE THREAD

**Issue by ctf0** [absszero/vscode-laravel-goto#1]
is it possible to get it to work under blade files as well ?

**on a side note:**
using `ctrl+click` would be much better and more convenient than using a command.

**Comment by absszero** [comment]
It should work on any *.php files, what's your situation?

`ctrl+click` is great, but vscode does not support binding mouse with keyboard currently.
check it https://github.com/microsoft/vscode/issues/3130

**Comment by ctf0** [comment]
using the shortcut on something like `config` in blade, do nothing

**Comment by absszero** [comment]
this's my example `hello.blade.php`, and it works fine, did i miss something?
```blade
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
{{ Config::get('app.timezone'); }}
{{ config('app.timezone'); }}
</body>
</html>

**Comment by ctf0** [comment]
okay found the issue, `alt+;` doesnt work under blade for some reason, thanx for ur help.

**Comment by ctf0** [comment]
regarding the `alt+click` vscode support it but u will need to change a lot of ur code to use it
check https://code.visualstudio.com/api/references/document-selector

**Comment by absszero** [comment]
thank you, I'll try it

**Comment by ctf0** [comment]
ps: maybe we should have a new ticket for the new feature ?
