### ISSUE TITLE
Is it possible to make it to work with Inertia?

### ISSUE THREAD

**Issue by nezaboravi** [absszero/vscode-laravel-goto#17]
WOuld be great to add go to file rendered by Inertia
eg
` return Inertia::render('Admin/Transactions');`
 
 These will be vue  file in my case, altho it can be react or svelte.

**Comment by absszero** [comment]
I published a new version v4.6 to support  Inertia.js
```php
return Inertia::render('Auth/Login'); 
//  goto Auth/Login
