### ISSUE TITLE
Possibly too aggressive lookup for component

### ISSUE THREAD

**Issue by pistvan** [absszero/vscode-laravel-goto#20]
I think `viewPlace` in `Finder` may be too aggressive when looking for a matching token. I'm not sure to be honest.

But I can get hovers like this, which is syntactically nonsense:
![image](https://github.com/absszero/vscode-laravel-goto/assets/10829764/17557621-7f73-4640-ac77-cfa36180ff43)

Why not use a regex like `/view\((['"])([^'"])\1/`?

(I disabled every other extension for testing.)

**Comment by absszero** [comment]
Hi, Pistvan,

I'v released a version to enhance search for view and component, thank you~
