### ISSUE TITLE
Extension Crashes VSCode in AppServiceProvider.php - Bug Report

### ISSUE THREAD

**Issue by heyyoudev** [absszero/vscode-laravel-goto#23]
Firstly, kudos for the extension's great work! However, I've had to disable it recently due to a recurring issue causing VSCode to crash. The problem seems to stem from the following code snippet within the `register `method of `app/Providers/AppServiceProvider.php`:

```
   public function register()
   {
       if ($this->isStageEnvironment()) {
           $this->app->singleton(Generator::class, function () {
               $instance = \Tests\Utils\CustomFaker\FakerFactory::create(config('app.faker_locale'));
               $instance->seed('1234');
               return $instance;
           });
       }
   }
```

Moreover, please note that the faker_locale key does exist inside `config/app.php`.

In addition to resolving this issue, it would be immensely helpful if the extension implemented a failsafe. For instance, if the file isn’t found or an error occurs, it could trigger a warning message in VSCode instead of causing a crash. Identifying this as the root cause of the crash was quite cumbersome, so having a warning message would greatly assist in troubleshooting.

I'm eager for a resolution as this extension has been of great help. Thanks in advance for addressing this!

**Comment by absszero** [comment]
Hi, Thank you for the report.

I copied the code to my AppServiceProvider, and also delete the faker_locale key in the config/app.php.
But I can't reproduce the result.

Recently, I introduced two features that needs to load files and to run a php process. it may cause the issue.
I uploaded a version to you, please remove Laravel Goto extension, and install it from the vsix file.
[vscode-laravel-goto-4.25.0.vsix.zip](https://github.com/absszero/vscode-laravel-goto/files/13698604/vscode-laravel-goto-4.25.0.vsix.zip)

After that, please add below configures to your setting.json. 

```json
"laravelGoto.disable_middleware": true,
"laravelGoto.disable_router_helper": true
```

Try it again and let me know if it works. (Please cross-test which setting is effective)
If that doesn't work, I may need your help to provide more detail.

**Comment by gaadeveloper** [comment]
Thank you for your prompt response.

I want to clarify that in my initial report, I mentioned that the faker_locale key does indeed exist in my `config/app.php` file. Apologies for any confusion caused earlier.

I attempted to apply the settings you suggested by adding them to my `settings.json`. However, upon doing so, these configurations appear grayed out, and hovering over them prompts an `"Unknown Configuration Setting"` error, even with the extension installed. Thus, I couldn't enable these settings.

To provide further context, the crash consistently occurs when I hover over `config ` or `create::` in the following line:

`$instance = \Tests\Utils\CustomFaker\FakerFactory::create(config('app.faker_locale'));
`

This issue persists even after attempting the provided settings adjustment. If there's additional information or troubleshooting steps that could help, please let me know. I'm keen to assist in any way to resolve this issue.

**Comment by absszero** [comment]
Can you setup a new Laravel project, and try again?

This time, please install the release version.
https://marketplace.visualstudio.com/items?itemName=absszero.vscode-laravel-goto

**Comment by gaadeveloper** [comment]
I'm unable to test it on a new Laravel project as the specific scenario causing the crash doesn't come by default in Laravel setups.

However, I've conducted tests with no other extensions enabled, and unfortunately, the issue persists exactly as previously described:

![image](https://github.com/absszero/vscode-laravel-goto/assets/7956593/eff3285e-3651-4f94-9908-4dd9adde1038)

It's worth noting that recently, several team members encountered issues with this extension as well. Initially, they were uncertain about the cause of the crashes, as they seemed quite random. It took them some time to pinpoint that this extension was triggering the problem.

We've temporarily removed the extension from our company's VSCode profile. Hopefully, with future updates or revisions, we can reintroduce it.

Keep up the good work!

**Comment by absszero** [comment]
To understand what causes this problem, could you provide a smallest sample project to me, so I can reproduce the issue and fix it. Thank you.

**Comment by absszero** [comment]
> I'm unable to test it on a new Laravel project as the specific scenario causing the crash doesn't come by default in Laravel setups.
> 
> However, I've conducted tests with no other extensions enabled, and unfortunately, the issue persists exactly as previously described:
> 
> ![image](https://private-user-images.githubusercontent.com/7956593/291952722-eff3285e-3651-4f94-9908-4dd9adde1038.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NDQwMzcsIm5iZiI6MTcxMTg0MzczNywicGF0aCI6Ii83OTU2NTkzLzI5MTk1MjcyMi1lZmYzMjg1ZS0zNjUxLTRmOTQtOTkwOC00ZGQ5YWRkZTEwMzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzFUMDAwODU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzE5MjRkMmEyOWRjM2QyNmVlYWIxYmVhYjhjZGFmNDQwMDhiMzg5OGFlNjUzNDE0OGU3MDQ3NWYyMTZmYzdmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.b5JjcYz51mtNpSjXG9EmJRfwKlqGBDyaeoGaFvatVgo)
> 
> It's worth noting that recently, several team members encountered issues with this extension as well. Initially, they were uncertain about the cause of the crashes, as they seemed quite random. It took them some time to pinpoint that this extension was triggering the problem.
> 
> We've temporarily removed the extension from our company's VSCode profile. Hopefully, with future updates or revisions, we can reintroduce it.
> 
> Keep up the good work!

HI, I've fixed a bug of config helper recently.
Would you like to try again, thank you.

**Comment by heyyoudev** [comment]
The bug that made the whole VSCode crash does seem fixed.

What I have now observed is a minor, yet disruptive stylistic issue concerning the suggestions. When hovering over certain parts of the line where the config method helper is used, the suggestions displayed are inappropriate and irrelevant to the context.

Thank you for your continued support and maintenance.

![image](https://github.com/absszero/vscode-laravel-goto/assets/7956593/8755c3a7-0ac0-475e-abb9-8dd56c054404)

![image](https://github.com/absszero/vscode-laravel-goto/assets/7956593/80a27115-bf2b-4017-b258-212784c4940a)

**Comment by absszero** [comment]
Please install the latest version and try again

**Comment by heyyoudev** [comment]
It works perfectly now, great job. Thank you.
