### ISSUE TITLE
for some reason the extension stoped working

### ISSUE THREAD

**Issue by sacalito** [absszero/vscode-laravel-goto#32]
hi, first of all thankyou for your awsome extension.

the extension stoped working at all.

i disabled all other extensions uninstalled and reinstalled. activated the debug but nothing is showing in the console neither with Righ click -> laravel go to, nor with Alt + ;

where could i go to debug the error?

**Comment by sacalito** [comment]
> hi, first of all thankyou for your awsome extension.
> 
> the extension stoped working at all.
> 
> i disabled all other extensions uninstalled and reinstalled. activated the debug but nothing is showing in the console neither with Righ click -> laravel go to, nor with Alt + ;
> 
> where could i go to debug the error?

also in the output console on hosts both remote and local do not show anything

**Comment by absszero** [comment]
Hi, [sacalito](https://github.com/sacalito),

please provide more details.

OS:
How To Reproduce:
Expected Behavior:

**Comment by sacalito** [comment]
OS: Windows 10 
How To Reproduce: just install the plugin and conect to any ssh machine with a laravel instalation 
Expected Behavior: when pressing Alt + ; should open the file

image atached of all the plugins i have installed.

i didnt have intelesense and it didnt work either. (was working before without intelesense)

and after installing intelesense also did not work

any other info i need to give you?

im even willing to let you Remote Desktop into my computer so we can debug if neccesary. or where should i see the logs to debug?

this extension makes working with livewire so much fatser, im frustrated its not working anymore
![image](https://github.com/absszero/vscode-laravel-goto/assets/62297560/8d0a9dc5-2850-4021-905f-fce7eb3c07dc)

**Comment by absszero** [comment]
Could you please provide a smallest Laravel project, that I can reproduce the issue on my own environment?

**Comment by sacalito** [comment]
sure
https://github.com/sacalito/Laravel-Livewire-Error

**Comment by sacalito** [comment]
just remember i connect via ssh with the official microsoft ssh extension, dont know if makes a difference

**Comment by sacalito** [comment]
i just found out another interesting thing. when downgrading to v4.26.2 it starts to work again, any version after that (starting from v4.27.0) stops working

**Comment by absszero** [comment]
Thanks for the help, I will dig into the issue soon.

**Comment by absszero** [comment]
> i just found out another interesting thing. when downgrading to v4.26.2 it starts to work again, any version after that (starting from v4.27.0) stops working
> 
> i missed so much having your extension working!

Hi, I've release  the version 4.28.3. please install the new version. thank you.

**Comment by sacalito** [comment]
> > i just found out another interesting thing. when downgrading to v4.26.2 it starts to work again, any version after that (starting from v4.27.0) stops working
> > i missed so much having your extension working!
> 
> Hi, I've release the version 4.28.3. please install the new version. thank you.

you are awsome thankyou very much
