### ISSUE TITLE
Make it activated by blade files too, not only php

### ISSUE THREAD

**Issue by ciobanut** [absszero/vscode-laravel-goto#41]
The extension is activated in php files, but I want to use it in blade files as well. Because I use other extensions that do auto-formatting for the blade. Please, make it activated by blade files too.

Activated by `onLanguage:php` event: 1ms

My settings:
```
"files.associations": {
		"*.php": "php",
		"*.blade.php": "blade"
}
```

**Comment by absszero** [comment]
OK! Please install the version: 4.28.11.
