### ISSUE TITLE
react/typescript configurations

### ISSUE THREAD

**Issue by agelospanagiotakis** [absszero/vscode-laravel-goto#46]
i think it should take into account .tsx files for react/typescript configurations

for example
```
 return Inertia::render(component: 'admin/users/role', [
... 
]
 ```
should link to 
resources/js/pages/admin/users/role.tsx

**Comment by absszero** [comment]
Currently, when named parameters are not used, for example:

```
return Inertia::render('admin/users/role')
```

The tool is able to assist with navigating to the corresponding `admin/users/role` file through fuzzy search (regardless of the file extension).

I will work on support for cases where named parameters are used, like in your example. thank you.
